### ISSUE TITLE
Fix client side rendering

### ISSUE THREAD

**Issue by sumana2001** [Webwiznitr/project-jumpstart#18]
When we reload the page, before the preloader there is a snapshot of the website coming without CSS. 

https://user-images.githubusercontent.com/63084088/130243048-ce5aa42d-e556-40b3-bede-d6d60c792b51.mov

**Comment by mohankumar27** [comment]
@sumana2001  can I take up this issue ?

**Comment by sumana2001** [comment]
@mohankumar27 Sure go ahead!

**Comment by mohankumar27** [comment]
@sumana2001 I have raised PR #23 for this issue. 

Kindly review it.
